// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaylKoyn.Data.Models;

#nullable disable

namespace PaylKoyn.Data.Migrations
{
    [DbContext(typeof(PaylKoynDbContext))]
    partial class PaylKoynDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argus.Sync.Data.Models.ReducerState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestIntersectionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartIntersectionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("ReducerStates", "public");
                });

            modelBuilder.Entity("PaylKoyn.Data.Models.Entity.OutputBySlot", b =>
                {
                    b.Property<string>("OutRef")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Raw")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ScriptDataHash")
                        .HasColumnType("text");

                    b.Property<string>("ScriptHash")
                        .HasColumnType("text");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("SpentSlot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("SpentTxHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OutRef");

                    b.HasIndex("Slot");

                    b.HasIndex("SpentSlot");

                    b.HasIndex("SpentTxHash");

                    b.ToTable("OutputsBySlot", "public");
                });

            modelBuilder.Entity("PaylKoyn.Data.Models.Entity.TransactionBySlot", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Hash");

                    b.HasIndex("Slot");

                    b.ToTable("TransactionsBySlot", "public");
                });

            modelBuilder.Entity("PaylKoyn.Data.Models.Entity.TransactionSubmission", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<decimal?>("ConfirmedSlot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("DateSubmitted")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TxRaw")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Hash");

                    b.HasIndex("DateSubmitted");

                    b.HasIndex("Status");

                    b.ToTable("TransactionSubmissions", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
