// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaylKoyn.ImageGen.Data;

#nullable disable

namespace PaylKoyn.ImageGen.Migrations
{
    [DbContext(typeof(MintDbContext))]
    partial class MintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PaylKoyn.ImageGen.Data.MintRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdaFsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("MintTxHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("NftMetadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NftNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Traits")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadPaymentAddress")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UploadPaymentAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NftNumber")
                        .IsUnique();

                    b.ToTable("MintRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
